import Head from "next/head";
import Header from "@components/Header";
import Footer from "@components/Footer";
import { getTextWithDotPointsForHome } from "@components/contentful/textWithDotPoints";
import { getHeroImageForHome } from "@components/contentful/heroImage";
import { getTextContentsForHome } from "@components/contentful/textContents";
import { getFAQPreviewContentsForHome } from "@components/contentful/faqPreviewContents";
import { getLegalSubstantiationContentsForHome } from "@components/contentful/legalSubstantiation";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";

export default function Home({
  preview,
  textWithDotPoints,
  heroImages,
  textContents,
  faqPreviewContents,
  legalSubstantiationContents,
}) {
  const heroImage = heroImages[0];
  const textWithDotPoint = textWithDotPoints[0];
  const faqPreviewContent = faqPreviewContents[0];
  const legalSubstantiationContent = legalSubstantiationContents[0];

  // const client = createClient({
  //   space: process.env.nettstNEXT_PUBLIC_CONTENTFUL_SPACE_ID,
  //   accessToken:
  //     process.env.nettstIS_PREVIEW === "true"
  //       ? process.env.nettstCONTENTFUL_PREVIEW_TOKEN
  //       : process.env.nettstCONTENTFUL_DELIVERY_TOKEN,
  // });

  // // Alternatively you can use the CDN API as follows...
  // const baseUrl =
  //   process.env.NEXT_PUBLIC_IS_PREVIEW === "true"
  //     ? "preview.contentful.com"
  //     : "cdn.contentful.com";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="ic-info">
        <header className="ic-info-header">
          <img
            src={heroImage.mobileImage.url}
            className="ic-info-banner ic-mobile-only"
          />
          <img
            src={heroImage.desktopImage.url}
            className="ic-info-banner ic-desktop-only"
          />
        </header>

        <div className="ic-info-grid">
          <div className="ic-info-section ic-info-section__what-is-ic">
            <h1>{textWithDotPoint.heading}</h1>

            <div className="ic-info-section-columns">
              <div className="ic-info-section-columns__column">
                <div className="ic-info-section-copy">
                  {documentToReactComponents(textWithDotPoint.body.json)}
                </div>

                <div className="ic-desktop-only">
                  <a
                    href={textWithDotPoint.ctaUrl}
                    className="ic-button-solid ic-button-solid--arrow"
                    target="_blank"
                    rel="noopener"
                  >
                    {textWithDotPoint.ctaText}
                    <svg
                      width="14"
                      height="14"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M7 .333 5.827 1.508l4.65 4.659H.334v1.666h10.142l-4.65 4.659L7 13.667 13.667 7 7.001.333Z"></path>
                    </svg>
                  </a>
                </div>

                <div className="ic-info-app-stores ic-mobile-only">
                  <a
                    href="https://onelink.to/hdsweq"
                    target="_blank"
                    rel="noopener"
                  >
                    <img
                      src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/app-store-button.svg"
                      alt="Download on the App Store"
                    />
                  </a>
                  <a
                    href="https://onelink.to/hdsweq"
                    target="_blank"
                    rel="noopener"
                  >
                    <img
                      height="48"
                      src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/google-play-button.png"
                      alt="Get it on Google Play"
                    />
                  </a>
                </div>
              </div>
              <div className="ic-info-section-columns__column">
                {documentToReactComponents(textWithDotPoint.dotPoints.json)}
              </div>
            </div>
          </div>
          <div className="ic-info-section ic-info-section__how-it-works">
            <h2>{textContents[0].heading}</h2>
            {documentToReactComponents(textContents[0].body.json)}
          </div>
          <div className="ic-info-section ic-info-section__our-doctors">
            <h2>{textContents[1].heading}</h2>
            <div className="ic-info-section-copy">
              {documentToReactComponents(textContents[1].body.json)}
            </div>
          </div>
          <div className="ic-info-section ic-info-section__faq">
            <h2>{faqPreviewContent.heading}</h2>

            <div className="ic-info-section-columns">
              <div className="ic-info-section-columns__column">
                <div className="ic-info-section-copy">
                  {documentToReactComponents(faqPreviewContent.body.json)}
                </div>
                <div className="ic-faq">
                  {faqPreviewContent.faQsCollection.items.map((faq, index) => (
                    <details key={`faq_${index}`}>
                      <summary>
                        {faq.faqTitle}
                        <svg
                          width="12"
                          height="8"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path d="M1.41.551 6 5.131l4.59-4.58L12 1.961l-6 6-6-6L1.41.551Z"></path>
                        </svg>
                      </summary>
                      <div className="ic-faq__answer">
                        {documentToReactComponents(faq.faqBody.json)}
                      </div>
                    </details>
                  ))}
                </div>
              </div>
            </div>
          </div>
          <div className="ic-info-section ic-info-section__speak-to-doctor">
            <h2>{textContents[2].heading}</h2>
            <div className="ic-info-section-copy">
              {documentToReactComponents(textContents[2].body.json)}
            </div>
            {textContents[2].ctaVisible && (
              <div className="ic-desktop-only">
                <a
                  href={textContents[2].ctaUrl}
                  className="ic-button-solid ic-button-solid--arrow"
                  target="_blank"
                  rel="noopener"
                >
                  {textContents[2].ctaText}
                  <svg
                    width="14"
                    height="14"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M7 .333 5.827 1.508l4.65 4.659H.334v1.666h10.142l-4.65 4.659L7 13.667 13.667 7 7.001.333Z"></path>
                  </svg>
                </a>
              </div>
            )}
            <div className="ic-info-app-stores ic-mobile-only">
              <a
                href="https://onelink.to/hdsweq"
                target="_blank"
                rel="noopener"
              >
                <img
                  src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/app-store-button.svg"
                  alt="Download on the App Store"
                />
              </a>
              <a
                href="https://onelink.to/hdsweq"
                target="_blank"
                rel="noopener"
              >
                <img
                  height="48"
                  src="https://static.chemistwarehouse.com.au/ams/media/images/instant-consult/google-play-button.png"
                  alt="Get it on Google Play"
                />
              </a>
            </div>
          </div>

          <div className="ic-info-section">
            <div>{legalSubstantiationContent.heading}</div>
            <div>
              {documentToReactComponents(legalSubstantiationContent.body.json)}
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export async function getStaticProps({ preview = false }) {
  const heroImages = (await getHeroImageForHome(preview)) ?? [];
  const textWithDotPoints = (await getTextWithDotPointsForHome(preview)) ?? [];
  const textContents = (await getTextContentsForHome(preview)) ?? [];
  const faqPreviewContents =
    (await getFAQPreviewContentsForHome(preview)) ?? [];
  const legalSubstantiationContents =
    (await getLegalSubstantiationContentsForHome(preview)) ?? [];

  return {
    props: {
      preview,
      heroImages,
      textWithDotPoints,
      textContents,
      faqPreviewContents,
      legalSubstantiationContents,
    },
  };
}
